Palashio/libra

data generation/dataGen.py, preprocessing/data_preprocesser.py, queries/predictionQueries.py
Updated 3 files: dataGen.py, data_prerprocesser.py, predictionQueries.py
predictionQueries.py-> Instead of lists ImageDataGenerator used and Augmentation of the images implemented.
data_prerprocesser.py-> Removed the functions for image preprocessing as they are already being done during modeling 
dataGen.py-> Data saving folder: Training_set or Test_set/Word/Image_file(Done for smooth working of the ImageDataGenrator)
=> Sarthak dev1

data generation/dataGen.py, preprocessing/data_preprocesser.py, queries/predictionQueries.py
=> Revert "Sarthak dev1"

plotting/generatePlots.py, queries/predictionQueries.py
Added the plot_corr() function and setting the default value to show correlation for all data variables.
Deleted the Accuracy and Loss plots from the majority of the functions and added them as separate common to all plots.
Deleted recurrence libraries.
=> Added functions in generatePlot.py

preprocessing/data_preprocesser.py, queries/predictionQueries.py
Uses median strategy on numeric columns and creates column for NaNs in categorical columns.
Closes #35
=> Add Imputer to structured_preprocessor

queries/predictionQueries.py
in the `initial_preprocesser()` added the functionality to remove columns where each element in the column is unique to account for ID's
=> added removing id columns

preprocessing/data_preprocesser.py, queries/predictionQueries.py
Added prototype predict() function and changed structured_preprocesser() to return the fit preprocessing pipeline. Also added elements to model dictionary to enable predictions. 
Closes #58
=> Create predict() and change structured_preprocesser() to use Pipelines

tools/Additional Resources.md, tools/Example Projects.md, tools/Reference Manual.md
Worked on implementing .md files delineating materials relevant for comprehending/utilizing Libra
=> LibraReferenceManualExampleProjectsAdditionalResources

libra/preprocessing/data_preprocesser.py, libra/queries/dimensionality_red_queries.py, libra/queries/prediction_queries.py
=> Switch from MCA to CA and set CA to use optimal n_components

docker/Dockerfile, docker/Makefile, docker/README.md
Initial Dockerfile, makefile and readme. I might change some of the code tomorrow after testing
=> Yash himmatramka

libra/queries/prediction_queries.py
=> Store latest_model and fix text default param value

libra/preprocessing/data_reader.py, libra/preprocessing/image_preprocesser.py, libra/queries.py, libra/query/feedforward_nn.py, libra/query/unused_functions.py
---
name: b) Added modularity to CNN
about: Select this if you're adding a new feature to Libra.
labels: Data
---
more customization for user, epochs, preprocess...
added default parameters and had different processes depending on dataset
=> Added modularity to CNN

libra/preprocessing/data_preprocesser.py, libra/queries.py, libra/query/classification_models.py, tools/materials/Reference Manual.md
Added hyperparameters, removed particular bugs, and added documentation regarding data preprocessor methods in Libra reference manual.
=> Hyperparameters update

libra/preprocessing/data_preprocesser.py, libra/queries.py, libra/query/feedforward_nn.py
Also fixes issue with models not being appended to model_data after fitting
Changed neural net query to look at unique values to determine whether the problem is a classification one or a regression one.
Taking value counts of the target due to string and float issues and used the length of that object.
Run it
=> Set neural net query to use at most 50 classes for classification

libra/preprocessing/data_reader.py
---
about: Select this if you're adding a new feature to Libra.
---
=> Removed Stratification References from Doc

libra/queries.py
---
name: b) Added default functionality if utility functions are called without a specific model 
---
Defaults for utility functions
Used the latest model field of the client class
Call functions on client without any model specified 
=> Added defaults to utility functions

libra/modeling/tuner.py, libra/plotting/generate_plots.py, libra/queries.py, libra/query/classification_models.py, libra/query/unused_functions.py
Kmeans log table added
Updated tuner added to unused functions
=> Logger update

libra/preprocessing/data_preprocesser.py, libra/queries.py
Text columns needed to be added to a final case in column name generation
Added it to the missing clause
Run code
=> Have text columns added in all cases of column name generation

libra/preprocessing/image_preprocesser.py, libra/queries.py, libra/query/feedforward_nn.py
---
---
combined read modes "pathwise" and "namewise" because was repetitive
created read mode called "csvwise"
gave client path to directory containing csv file, did one test without specifying the read_mode and another time specifying it
=> Combined "pathwise" and "namewise" to be "csvwise"

libra/queries.py, requirements.txt
---
---
added ssl verification
=> added ssl verification

libra/plotting/generate_plots.py, libra/queries.py
=> Add save_model to .analyze()

tools/materials/Reference Manual.md
Fixed some reference manual documentation regarding functions in plotting segment of Libra
=> Update Reference Manual.md

libra/queries.py
=> Change modelKey to model

libra/queries.py, libra/query/nlp_queries.py
---
---
Added data reader class to nlp queries
Used the class instead of read csv from pandas
Tested all queries again
=> added data reader class to nlp queries

libra/queries.py
=> changed parameter name that was not updated

libra/preprocessing/NLP_preprocessing.py, libra/queries.py, libra/query/nlp_queries.py, requirements.txt
---
name: b) Added label column parameter
---
Added label column parameter
Enabled user to customize finding target column when column headers are not standard
Tested new parametarization
=> Changed requirements and added label column parameter to nlp queries

libra/modeling/tuner.py, libra/query/feedforward_nn.py, libra/query/supplementaries.py
=> Revert "Updated feedforeward_nn"

libra/plotting/generate_plots.py, libra/queries.py, libra/query/classification_models.py, libra/query/feedforward_nn.py
Adjusts all functions to account for this change, and fixes bugs in .analyze()
Closes #210
=> Replace dicts in sklearn models  with LabelEncoders

libra/modeling/prediction_model_creation.py
=> Modified Dense Layer @ Lines 36 & 71

libra/plotting/generate_plots.py
=> Updated To Comprehensions

libra/data_generation/dataset_labelmatcher.py
=> Updated To Comprehensions-dataset_labelmatcher.py

libra/dev_pipeliner/regression_split_functions.py
=> Updated To Comprehensions-regression_split_functions.py

libra/preprocessing/NLP_preprocessing.py, libra/preprocessing/huggingface_model_finetune_helper.py, libra/preprocessing/image_caption_helpers.py, libra/query/nlp_queries.py
---
name: Fixed NLP helper doc
---
This pull request closes #284 .
Added better comments and improved some helper functions
By adding more descriptive comments to guide new developers
No tests needed
=> Nlp helper fix

libra/preprocessing/image_preprocesser.py, libra/query/feedforward_nn.py
---
name: b) CNN can support gray scale image datasets
---
CNN can process gray scale images efficiently
Tracked if all the images in the dataset were gray scale images, by checking if all the channels were the same
=> CNN can support gray scale data sets

.gitignore, libra/datasets.py, requirements.txt
---
name: Downloading sample data sets
about: Allows user to load in sample datasets from the web
---
This pull request closes #226 .
allow user to load in data set by specifying the name from the list of our sample data sets
downloads from our mediafire links
```
from libra import datasets  
data = datasets.load('housing')
```
=> Download feature for sample datasets

docker/Dockerfile, docker/README.md, docker/theanorc
Added docker image for python3.6, and updated README to reflect those changes
=> Docker and README changes

libra/query/feedforward_nn.py
---
name: b) Updated base CNN architecture and changed fit to fit_generate
---
This pull request closes #285  .
Tested different CNN models to find most optimal model
Ran different CNN models updating the Conv2d, MaxPooling, Drop, etc...
Changed filter size and number...
=> Updated base CNN architecture and changed fit to fit_generate

libra/queries.py, libra/query/classification_models.py
---
name: Silence warning messages
---
Silenced the warning messages created by some wrong parameter use.
Removed that parameter so that XGBoost can automatically select that parameter when to use and added verbosity to silent warning messages.
Running the tests
=> Silence XGBoost warnings

.gitignore, libra/datasets.py, setup.py
Update dataset links with official mediafire account
updated links in datasets.py
import a dataset
=> Update dataset links with official mediafire account

requirements.txt
This pull request adds version of transformers to libra requirement. @Palashio, could you please take a look at it?
=> Updated requirements file to have version of transformers

libra/modeling/prediction_model_creation.py, libra/query/feedforward_nn.py, tests/tests.py
Fixing issues with binary classification
=> Ann class issue

tests/tests.py
=> commenting out gan test in tests.py

libra/query/feedforward_nn.py
---
Name: Added more pre-trained models
About: Select this if you're adding a new feature to libra.
Labels: Feature
---
This pull request closes #352  .
Added more pre-trained models compatibility.
=> Added more pretrained models 🎉

libra/query/feedforward_nn.py
Looks like legacy LOC left from early development
=> Clean up default (non-pretrained) CNN model code
